#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

echo "${YELLOW}Building NixOS configuration...${NC}"
sudo nixos-rebuild switch --extra-experimental-features 'nix-command flakes' --flake . "$@"

echo "${GREEN}Build and switch complete!${NC}"